### ISSUE TITLE
optics namespace is not properly used by the poller

### ISSUE THREAD

**Issue by contested-space** [rkallos/erl-optics#4]
## Expected Behavior
The poller should either return only the values from it's specific optics namespace or all the values, properly identified.

## Current Behavior
The poller returns all the lenses from all the optics namespaces, without distinction. If two optics namespace contain a lens similarly named, only one will be returned by the poller.

## Possible Solution
Either specify which optics namespace to look for and return only those lenses, or return all the lenses with a more informative key-value containing the namespace

## Steps to Reproduce
1. To show that all the lenses are read:
```
    1> erl_optics:start(<<"test">>, [erl_optics_lens:counter(<<"c-test">>)]).                                  
    ok
    2> erl_optics:poll().                                                                                      
    {ok,#{<<"c-test">> => 0}}

    <quit interpreter>

    1> erl_optics:start(<<"test-2">>, [erl_optics_lens:counter(<<"c2-test">>)]).
    ok
    2> erl_optics:poll().                                                       
    {ok,#{<<"c-test">> => 0,<<"c2-test">> => 0}}
```

2. To show that only one of duplicate lenses are read:
```
    1> erl_optics:start(<<"test-1">>, [erl_optics_lens:counter(<<"c-test">>)]). 
    ok

    <quit interpreter>

    1> erl_optics:start(<<"test-2">>, [erl_optics_lens:counter(<<"c-test">>)]). 
    ok
    2> erl_optics:poll().                                                      
    {ok,#{<<"c-test">> => 0}}
```

**Comment by avanier** [comment]
This issue is of particular concern if different applications using `erl-optics` are going to be colocated.

**Comment by contested-space** [comment]
The map returned by the poller now has keys of the form <prefix>.<lens_name >, so lenses from different optics namespaces are different.
